# The tests in this file consist of paired input files from official examples
# and corresponding output files generated by running the official version of MMA,
# serving to ensure consistency before and after the refactoring in this fork.

import mido
import pytest
import pathlib
import pytest
import pytest_console_scripts
import os

def assert_midi_equal(midi1, midi2):
    assert len(midi1.tracks) == len(midi2.tracks), "Number of tracks differ"
    for track1, track2 in zip(midi1.tracks, midi2.tracks):
        assert len(track1) == len(track2), "Number of messages in track differ"
        for msg1, msg2 in zip(track1, track2):
            assert msg1.type == msg2.type, f"Message types differ: {msg1} vs {msg2}"
            assert msg1.time == msg2.time, f"Message times differ: {msg1.time} vs {msg2.time}"
            if hasattr(msg1, 'note'):
                assert msg1.note == msg2.note, f"Notes differ: {msg1.note} vs {msg2.note}"
            if hasattr(msg1, 'velocity'):
                assert msg1.velocity == msg2.velocity, f"Velocities differ: {msg1.velocity} vs {msg2.velocity}"

root = pathlib.Path(__file__).parent / "files"
temp = pathlib.Path(__file__).parent.parent / "testtemp"

@pytest.mark.parametrize("input_file, expected_output_file", [
    ("after.mma", "after.mid"),
    ("deep-river.mma", "deep-river.mid"),
])
def test_mma(input_file, expected_output_file, script_runner):
    input_path = root / input_file
    expected_output_path = root / expected_output_file
    actual_output_path = temp / expected_output_file
    os.makedirs(actual_output_path.parent, exist_ok=True)
    os.chdir(root)

    # Run the MMA script with the input file
    result = script_runner.run(["neomma", str(input_path), "-f", str(actual_output_path)])
    assert result.success, f"Script failed with error: {result.stderr}"

    # Load the generated MIDI file and the expected MIDI file
    generated_midi = mido.MidiFile(str(actual_output_path))
    expected_midi = mido.MidiFile(str(expected_output_path))

    # Assert that the generated MIDI matches the expected MIDI
    assert_midi_equal(generated_midi, expected_midi)